### ISSUE TITLE
Flatpicker is not responsive

### ISSUE THREAD

**Issue by likeabas** [Laratipsofficial/laravel-flatpickr#20]
First of all: thanks for the great package!

When using I encountered a small bug. The flat picker is not responsive and this causes problems on mobile when you set the visibleMonths > 1.

I have fixed this myself by using my own cloned flatpicker.css file and adding the following code to the bottom:

```

/* Let's make it responsive! */

@media screen and (max-width: 620px) {
    .flatpickr-months .flatpickr-month:nth-of-type(2),
    .flatpickr-innerContainer .flatpickr-weekdaycontainer:nth-of-type(2),
    .flatpickr-innerContainer .dayContainer:nth-of-type(2){
        display: none;
    }
    .flatpickr-days,
    .flatpickr-calendar
    {
        max-width: 311px;
    }

}
```

I still wanted to report the issue, because I think it can be easily fixed the the code above.

Please keep in mind that this code only solves the issue for 2 visible months. But you can quite easily adjust it to accommodate for more months as well.

**Comment by Laratipsofficial** [comment]
Thank you very much for the css fixes.
However, this package just aims to only use the default things provided by flatpickr to make it as minimal and customizable as possible.
