### ISSUE TITLE
Localize Plugin

### ISSUE THREAD

**Issue by kennethenglisch** [Laratipsofficial/laravel-flatpickr#25]
Hello,
is it possible to localize the plugin with the provided languages from flatpickr/flatpickr?

I couldn't find a way to use your plugin, which is amazing, and use the official localization files. I need the plugin to work in German as well.

Thanks in advance.

**Comment by Laratipsofficial** [comment]
Hi @kennethenglisch ,

Thanks for creating this issue. 

For now, you can do it like this:
```html
<head>
    <x-flatpickr::style />
</head>

<body>
    <x-flatpickr :config="[
        'locale' => 'de',
    ]" />

    <x-flatpickr::script />
    <script src="https://npmcdn.com/flatpickr/dist/l10n/de.js"></script>
</body>
```

**Comment by Laratipsofficial** [comment]
Thanks @kennethenglisch 

I have now implemented the locale functionality. You can add this in the .env file and you will be good to go.
```env
FLATPICKR_LOCALE=de
```

You will find the list of locales here: https://github.com/flatpickr/flatpickr/tree/master/src/l10n

**Comment by kennethenglisch** [comment]
Thank you for implementing this feature.
I just changed my locale through the .env to "de" and have encountered a bug.

When I set a value for example '18.03.2024 to 19.03.2024' (german date format) and I have the german locale selected, only the first date will be inserted into the input field and the end date won't be filled in.
If I change back the locale to default the bug is gone and the input field is filled normally.

**Comment by AshishDhamalaAD** [comment]
@kennethenglisch 
If you mention a code that could create a reproducible bug, then it will be easier to solve the bug.

**Comment by jcabanillas** [comment]
Hello,
Good job!

When I set the date in spanish language (dd/mm/yyyy a dd/mm/yyyy):
<x-flatpickr range date-format="d/m/Y" name="rango_fecha" id="rango_fecha" value="01/10/2024 a 31/10/2024" />
I have an error:
The two dates must be string and separated by ' to ' in between.

How can I fix it?
