### ISSUE TITLE
Flatpickr doesn't open on second date select

### ISSUE THREAD

**Issue by dcbndev** [Laratipsofficial/laravel-flatpickr#9]
I am trying to add flatpickr as a date filter for a model. It works well only on first time usage. On first click, it opens and picks the clicked date, then closes. When I try to change the selected date, it doesn't open and works as a simple input and needs to reload the page to work again.

I do all these actions inside a full page livewire component.

Laravel 9 & Livewire.

**Comment by MiloudiMohamed** [comment]
I ran into the same issue, when I submit the form and for example the validation failed, the `Flatpickr` input turns into a normal `text input`

The work around here is to pass `altInput => false` config to the component

```html
<x-flatpickr
  ...
  :config="[
    'altInput' => false,
  ]"
/>
```

hope this helps someone until this issue gets fixed.

**Comment by Laratipsofficial** [comment]
Hey guys, thanks for creating the issue. It is now solved.
